### ISSUE TITLE
Isolate framework namespace from components

### ISSUE THREAD

**Issue by dragoonis** [ppi/framework#124]
Everything inside PPI will become PPI\Framework. For example: 
``PPI\ServiceManager`` will go into ``PPI\Framework\ServiceManager``

Composer autoloading alias to take ``PPI\*`` into ``PPI\Framework\*``

**Comment by noisebleed** [comment]
I'll fake this one @dragoonis

**Comment by dragoonis** [comment]
@noisebleed assigned myself.

**Comment by dragoonis** [comment]
@noisebleed roger that.

**Comment by noisebleed** [comment]
Branch [feature/124-isolate-framework-namespace-from-components](https://github.com/ppi/framework/tree/feature/124-isolate-framework-namespace-from-components).

**Comment by noisebleed** [comment]
Merged into develop.

**Comment by dragoonis** [comment]
:+1:
