### ISSUE TITLE
Making PPI Module Routing Multi-Vendor

### ISSUE THREAD

**Issue by dragoonis** [ppi/framework#37]
One of the key points about PPI is to alleviate vendor-lockin. This means your PPI module can be using ZF2 routing, SF2 routing or li3 routing (to name a few).

As demonstrated in this example, $module->getRoutes() will always return a symfony2 RouteCollection:
https://github.com/ppi/skeletonapp/blob/master/modules/Application/Module.php#L18

This is great as an initially working implementation, but the idea is to let the developer on a per-module basis choose which routing he/she wants.

I'm keen to hear people's ideas/patterns on making an extensible matching system that will do, "oh this module is using symfony, lets ask symfony to match it", which is what it currently does. It must detect a Zend2 route collection and ask ZF2 to match it.. and so on.

**Comment by noisebleed** [comment]
@dragoonis are you able to pull some documentation for 2.1.0?

**Comment by dragoonis** [comment]
Symfony and Aura routers completed.
I will work on docs.

**Comment by dragoonis** [comment]
Done.
